# Copyright 2010, 2011 Felix E. Klee <felix.klee@inka.de>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

application: realitybuilder
version: 11
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- remote_api: on

handlers:
- url: /
  static_files: index.html
  upload: index.html

# For proprietary components such as FlashCanvas:
- url: /proprietary
  static_dir: proprietary

# For development:
- url: /source
  static_dir: source

# For development:
- url: /documentation
  static_dir: documentation

- url: /javascript
  static_dir: javascript

- url: /demo/stylesheets
  static_dir: demo/stylesheets

- url: /demo/javascript
  static_dir: demo/javascript

- url: /demo/images
  static_dir: demo/images

- url: /demo/admin
  script: demo/main.py
  login: required # admin check is done separately

- url: /demo
  script: demo/main.py

# RPC for administration:
- url: /admin/rpc/.*
  script: main.py
  login: admin
  secure: always

- url: /.*
  script: main.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^source$
- ^documentation$
- ^LICENSE$
- ^NOTICE$
- ^README$
